name: tests

on: [push]

jobs:
  run_tests:
    runs-on: macos-13.6
    strategy:
      matrix:
        include:
          - xcode: "15.0"
            ios: "17.0"
          - xcode: "13.1"
            ios: "15.0"
    name: test iOS (${{ matrix.ios }})
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_$.app && /usr/bin/xcodebuild -version
    - name: Run unit tests
      run: xcodebuild test -scheme BudgetOnTheGo -project BudgetOnTheGo.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 13,OS=$' | xcpretty && exit ${PIPESTATUS[0]}
